### ISSUE TITLE
Sometimes slider of the horizontal scroll bar cannot appear

### ISSUE THREAD

**Issue by elmarlee** [TextAnalysisTool/Releases#101]
Thanks for this amazing analysis tool, I almost use it every day!

I find the slider of the horizontal scroll bar can't appear when I open some text files although they definitely contain long lines and I expect to have the slider and move it to the right to view the entire line.
The slider keeps missing even when I page down to the end of the file, or when I narrow the main window of the tool. "Show Only Filter Lines" can make the slider appear, but when I turn off this option to view the entire text file, the slider disappears.
This phenomenon can be duplicated for these kinds of files.

For most of the text files, the slider can appear as expected.

I'm using version 2020-12-17 on Windows 10 64 bit.

Thanks for your attention!

**Comment by elmarlee** [comment]
Looks like the total lines of the text files must be less than 26945 lines, otherwise the phenomenon I described above will happen.

**Comment by DavidAnson** [comment]
That's kind of an unusual number... Is there anything you can link to that would allow others to reproduce what you're seeing? Or can you outline the steps to produce a file that shows this behavior?

**Comment by elmarlee** [comment]
Yes, my files usually contain 20,000 lines or that level.
Now I guess it's because one line is too long, e.g. 49,423 characters. Would you please check the following text file? The slider doesn't appear on my computer.
[example.log](https://github.com/TextAnalysisTool/Releases/files/10738035/example.log)

**Comment by DavidAnson** [comment]
This should be fixed in the next release, thank you! (No ETA for now.)

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.

**Comment by elmarlee** [comment]
Thanks! The new release works quite well!
