### ISSUE TITLE
Changing a filter to Exclude and back resets its colors

### ISSUE THREAD

**Issue by mykael22000** [TextAnalysisTool/Releases#102]
If I have a filter set up with some colors and I change it to exclude, the lines it matches vanish. That's good.

If I subsequently remove the exclude setting the line reappear - but the filters color attributes have all reset to default.  

It would be great if I could keep the attributes, so I could hide some of my more common lines, find an interesting one, then display the surrounding lines as normal (without having to recolor the filter).

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.
