### ISSUE TITLE
A "System.ArgumentOutOfRangeException" of parameter "MaximumSize" window popup each time click "Add New Filter"

### ISSUE THREAD

**Issue by lixiaodao01** [TextAnalysisTool/Releases#106]
After I finished installing the APP, each time I  click "Add New Filter", a window popup telling that "System.ArgumentOutOfRangeException" of parameter "MaximumSize" in "System.Windows.Forms.Form.set_MaximumSize(Size value)".

Windows 11 OS with .net4.8 installed.

**Comment by DavidAnson** [comment]
Sounds like #103

**Comment by lixiaodao01** [comment]
> 

Yeah, it's same. I'll close this issue. Thanks.

**Comment by lixiaodao01** [comment]
Same with #103
