### ISSUE TITLE
First focus in new filter addition

### ISSUE THREAD

**Issue by dsp0105** [TextAnalysisTool/Releases#109]
In the latest (april 2023) version, when we say ctrl+N(to add a new filter), the focus is set to "Filter" field and not "text" field like it used to be in older versions.
Can we please have the default focus as before?

**Comment by vincec-msft** [comment]
A couple of us tried to reproduce this behavior but could not. The focus is always on the "text" field when the dialog is opened.

Could you try on different OS versions? There was another issue (#103 ) that only occurred on certain systems and we weren't able to reproduce that, either. In that case, though, we had a callstack so could guess at the issue and fix it. We might need explicitly set the focus but it would be nice to have a repro so we could ensure the fix actually worked.

**Comment by vincec-msft** [comment]
Also, if you have a version that focused on "text" and one that doesn't, on the same machine, I'd be interested to know their version numbers. Either from old versions you still have in your Downloads folder or from some of the really old versions in the download zip. Anything to help narrow down the problem.

**Comment by dsp0105** [comment]
Let me check and get back

**Comment by dsp0105** [comment]
sorry  for the delay in getting back,

on the same machine:
2023-04-25 --> issue is there
2020-12-17 - .NET 4.0 Release -- issue is not there

**Comment by dsp0105** [comment]
Actually, the issue got resolved itself, now when I add a new filter, the focus is on "Text" field.

Seems it learnt my preferences :-)

**Comment by howardgood88** [comment]
Hi, I also encountered this problem.
On the same machine, the file "TextAnalysisTool.NET\TextAnalysisTool.NET.exe" is not focused on "text" field by default, but the file "TextAnalysisTool.NET\2020-12-17 - .NET 4.0 Release\TextAnalysisTool.NET.exe" is OK.
