### ISSUE TITLE
really wish to display across multiple lines

### ISSUE THREAD

**Issue by WihauShe** [TextAnalysisTool/Releases#114]
It is unconvenient to look over one-line log by sliding the scroll bar, especially the line is massivly long. Also, it can not display the overview of the full line when the line is so much long exceeding the limit. My colleages hope it can display one long line entirely crossing multiple lines in the view, just with the same line number.

**Comment by DavidAnson** [comment]
Is this asking for word wrap? If not, I do not understand the suggestion.

**Comment by vincec-msft** [comment]
The request for word wrap is tracked in #68 

The lines are truncated just for display due to limitations of the listbox control. The full line is still used in filtering and copying.

**Comment by DavidAnson** [comment]
Closing as duplicate.
