### ISSUE TITLE
Remove older releases from the download zip

### ISSUE THREAD

**Issue by whihathac** [TextAnalysisTool/Releases#12]
We can remove the older versions/releases of the tool. This will reduce confusion as well as the download size.

**Comment by DavidAnson** [comment]
Older versions are included because they work in environments where the latest release does not. They're in subdirectories to keep them out of the way and overall download size is already quite small.

**Comment by whihathac** [comment]
Like due to a dependency on .NET versions?

**Comment by DavidAnson** [comment]
Right.
