### ISSUE TITLE
Allow disabling paste when a file is open

### ISSUE THREAD

**Issue by mattsnowboard** [TextAnalysisTool/Releases#18]
I've done this too many times. It's easy to copy something, then go to TextAnalysisTool and try to create a new filter (ctrl-n, ctrl-v) but accidentally just paste the text over your 500 MB open file.

It would be nice if I could at least disable paste, assuming it's a feature others actually use for something.

**Comment by tomers** [comment]
This happened to me several times, and it is a rather frustrating experience.
I suggest that a confirmation message box will pop whenever a text is pasted over an open file.

**Comment by DavidAnson** [comment]
Implemented in version 2016-01-08 (see Edit/Preferences).
