### ISSUE TITLE
Hits count doesn't refresh when open a new file with a filter

### ISSUE THREAD

**Issue by mskyongk** [TextAnalysisTool/Releases#20]
This is regression from previous version.

Build info: 2015-06-23

Repro steps:
1. Open a file and apply a filter
2. Ensure Hits columns show counts properly
3. Open a new file

Expected Result:
    Ensure Hits columns show counts should be updated properly

Actual Result:
    Ensure Hits columns show counts doesn't refresh and continue shows previous counts without doing 'Filters' -> 'Enable All Filters' which does refresh.

**Comment by DavidAnson** [comment]
This will fixed in an upcoming version, sorry for the trouble.

**Comment by DavidAnson** [comment]
Fixed in version 2016-01-08.

**Comment by mskyongk** [comment]
I just verified the fix. Thanks for fixing it.

**Comment by DavidAnson** [comment]
:) Credit goes to Vince Curley for the fix.
