### ISSUE TITLE
Drag and drop the progress bar in a large file, the bar will go back to upper place automatically.

### ISSUE THREAD

**Issue by wangfukai** [TextAnalysisTool/Releases#21]
Drag and drop the progress bar in a large file, the bar will go back to upper place automatically.

**Comment by DavidAnson** [comment]
Please see the second bullet of "Known Issues" in [ReadMe.txt](http://textanalysistool.github.io/ReadMe.txt):
> * The .NET Framework's improper handling of vertical and horizontal scrollbar
>   messages for ListBoxes can cause rendering problems for files with very many
>   or very long lines.

PS - I reproduced this in a 116,781 line file with version 2015-06-23. If you watch the line numbers, they wrap at or on 65536. (Also reproduces in version 2013-05-07.)

**Comment by DavidAnson** [comment]
This should be fixed in the `2020-12-17` release (thanks, Vince Curley!).
