### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by modulexcite** [TextAnalysisTool/Releases#22]
hi David, Is it possible to get the source  code for the application? I'm sure you have been asked about this a million times before and i apologize if you have already posted it somewhere.

**Comment by DavidAnson** [comment]
I open-source pretty much all my work, but TextAnalysisTool.NET is an exception due to a variety of historical reasons. Sorry about that!

**Comment by modulexcite** [comment]
I understand, thought I'd check. Thanks for your quick response.

___________________________
Thanks.




On Fri, Jan 8, 2016 at 8:52 PM -0800, "David Anson" <notifications@github.com> wrote:












Closed #22.
