### ISSUE TITLE
Display filter file name on the Windows frame.

### ISSUE THREAD

**Issue by WoodyKu** [TextAnalysisTool/Releases#23]
I use a number of predefined re-usable filter files that I load to quickly setup a filter. 
It would be nice to see which filter file is loaded. For example, the main file name is shown at the top Window frame and path\filename again at the bottom. One of them could be used to display the name of the filter file.
![image](https://cloud.githubusercontent.com/assets/16842267/12519677/36badd34-c10e-11e5-93b6-a7511d1f958c.png)

**Comment by DavidAnson** [comment]
Fixed in the 2016-06-16 release, thanks!
