### ISSUE TITLE
Download link does not contains latest versions

### ISSUE THREAD

**Issue by tomers** [TextAnalysisTool/Releases#25]
Download link in the application's homepage (https://textanalysistool.github.io/) contains the following URL: https://github.com/TextAnalysisTool/Releases/raw/master/TextAnalysisTool.NET.zip

The zip file contains the following directories:

- 2001-12-28 - x86 Release
- 2006-12-04 - .NET 1.1 Release
- 2013-05-07 - .NET 2.0 Release

The following directory is absent:
- Version 2016-01-08 for .NET 4+ (32- and 64-bit)

**Comment by DavidAnson** [comment]
Directories in the ZIP are used for older versions. The latest version is available in the root of the ZIP (i.e., the files that show up when the ZIP is first opened). Sorry for the confusion!
