### ISSUE TITLE
regular expression help link is broken

### ISSUE THREAD

**Issue by 14zywave** [TextAnalysisTool/Releases#31]
https://msdn.microsoft.com/library/en-us/cpguide/html/cpconcomregularexpressions.asp

**Comment by wangfukai** [comment]
I can't find the right way to use logic "and" in regular expression.   'A & B' and 'A && B' can't work.

**Comment by DavidAnson** [comment]
Thank you for pointing this out! I think the new link should be:
https://msdn.microsoft.com/en-us/library/hs600312.aspx

**Comment by DavidAnson** [comment]
Fixed in the 2016-06-16 release, thanks!
