### ISSUE TITLE
How to use logic 'and' in regular expression??

### ISSUE THREAD

**Issue by wangfukai** [TextAnalysisTool/Releases#33]
I can't find the right way to use logic 'and' in regular expression.   'A & B' and 'A && B' can't work.
Also the CSDN link in help documentation about regular expression is out of date.

**Comment by data-nerd** [comment]
This is a question about regular expressions, not TextAnalysisTool.net, but here you go:
Check out http://stackoverflow.com/questions/469913/regular-expressions-is-there-an-and-operator
The short answer is to use something like this: (?=.*word1)(?=.*word2)

**Comment by wangfukai** [comment]
Thanks very much! It work like this :  (?=.*Fukai)(?=.*Wang).
