### ISSUE TITLE
Settings don't always save

### ISSUE THREAD

**Issue by vincec-msft** [TextAnalysisTool/Releases#41]
As reported in a follow-on to issue #39, settings are not always saved. I could not reproduce this in my local installation but could when I ran TextAnalysisTool.NET on Simplified Chinese Windows.

When saving an ArgumentException is thrown when trying to delete the FontFamily registry key (which doesn't exist). Should be a straight-forward fix, but it'll be interesting to find out why it repros on one OS and not another.

**Comment by vincec-msft** [comment]
The problem occurs when we try to delete registry keys that don't exist. We delete a registry key when a setting is its default value, just to keep the registry clean.

As a work-around, change the Font Family to something other than Courier New and Zoom Percent to something other than 100%. This will cause the app to write those values to the registry rather than trying to delete the registry keys. Only these 2 settings need to be changed.

**Comment by DavidAnson** [comment]
Should be fixed in version 2017-01-24.
