### ISSUE TITLE
Not Support UTF-8 Chinese

### ISSUE THREAD

**Issue by great181855** [TextAnalysisTool/Releases#42]
Can TextTools Support UTF-8？  thanks a lot.  now  just support GBK
![notsupportutf-8](https://cloud.githubusercontent.com/assets/7201524/22925525/088a3078-f2e4-11e6-80aa-9c26ad16537c.png)

**Comment by DavidAnson** [comment]
Yes, TextAnalysisTool.NET supports UTF-8.

Does a file with bad rendering look good in Notepad? If so, does changing the font used by TextAnalysisTool help? (Some fonts don't include all characters and don’t fall back to good options.)

Can you please provide a file or text that is not being rendered correctly? (Either here or a URL.) Also, can you provide an image showing what you expect it to look like?

Thank you for your help!

**Comment by great181855** [comment]
Text not rendered correctly is below.
[android_log_for_TextTools.txt](https://github.com/TextAnalysisTool/Releases/files/779277/android_log_for_TextTools.txt)

We want look this below ,thank you very much.
![textanalysistool-help-ultraedit](https://cloud.githubusercontent.com/assets/7201524/23010550/fd3b7e92-f456-11e6-8d3d-dce8f3aed933.png)


changing the font , not work.
![textanalysistool-help](https://cloud.githubusercontent.com/assets/7201524/23010571/18a06e72-f457-11e6-9877-9aeb045c4179.png)

**Comment by DavidAnson** [comment]
The file you link to does not have a UTF-8 Byte Order Mark: https://en.wikipedia.org/wiki/Byte_order_mark

.NET doesn't do well auto-detecting the UTF-8 encoding without that.

If I open the file you link to in Windows Notepad, then File, Save As, "WithBom.txt", Encoding="UTF-8", and open the new file in TextAnalysisTool.NET, the rendering looks the same as you show above in UltraEdit.

This is on an EN-US Windows 10 OS without any localization packs installed, so the default font of "Courier New" is able to display the relevant Chinese characters.

If you're able to change the thing that creates your files to include the 3 bytes 0xEF,0xBB,0xBF at the beginning, you should be able to open them directly in TextAnalysisTool.NET.

Hope this helps!

**Comment by great181855** [comment]
Thank you a lot.  solve problems with patience. Can  TextAnalysisTool Open Source ?

**Comment by DavidAnson** [comment]
Great news!

And sorry that I'm not able to open-source the code at this time.
