### ISSUE TITLE
crash while loading new trace in an existing view with few filters on

### ISSUE THREAD

**Issue by manojbabulal** [TextAnalysisTool/Releases#44]
![text-analysis-tool-crash-on-loading-another-trace-log](https://user-images.githubusercontent.com/29309554/27435352-9aac8916-5779-11e7-99dc-e3c86921da3b.png)

**Comment by vincec-msft** [comment]
This was fixed in the 2019-01-03 release.

Readme:
* Fixed a bug that could cause a crash when changing files with active filters.
