### ISSUE TITLE
Add ability to set color pallette for filter window

### ISSUE THREAD

**Issue by kabiblueline** [TextAnalysisTool/Releases#47]
The main (text file) window seems fully customizable for color preferences through the config file settings.
Would it be possible to also change things in the filter window (text color, background, etc... ) ?

**Comment by dsp0105** [comment]
I second this request for enhancement, very much needed one please.

**Comment by vincec-msft** [comment]
Just to make sure I understand the request: you want the Colors and Fonts set in the Preferences to apply to the filter window as well as the main window?

**Comment by dsp0105** [comment]
Hi Vincec-msft, 

Thanks for getting back, let me explain the requirements:

1. Currently, if add a filter, then I can chose only from restricted set of colors for foreground/background, which is very limiting, since I have large number of filters (say 20) and don't have sufficient unique colors

2. Can we have the option to select any color (through color palette)?

Thanks!

**Comment by kabiblueline** [comment]
My original request was just that the colors and fonts apply to the filter window (as well as the main window) or possibly to allow separate customization of the filter window.
For example, if I have switched the main window to a "dark" theme (dark background, lighter text) the filter window still has a white background.

Additional choices for available colors of filtered text lines would also be good.

**Comment by vincec-msft** [comment]
Got it. 2 separate requests. I was thinking along the lines of what @kabiblueline proposed for this issue. We should have a new issue filed for @dsp0105's request. @dsp0105 would you mind filing that along with the  details you provided above? Thanks!

**Comment by dsp0105** [comment]
Sure, I will create a new issue. Thanks guys for a wonderful tool!

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.
