### ISSUE TITLE
Scroll bar doesn't work on large files

### ISSUE THREAD

**Issue by maro2511** [TextAnalysisTool/Releases#48]
Hi,
On large files (40MB+ / 100000+ lines), the scroll bar get stuck after reaching more or less a quarter of the file.
Page up/Page down button work fine.

Any idea way?

![capture](https://user-images.githubusercontent.com/9823106/32210839-76e27b8e-be18-11e7-814a-fa89a20710cf.PNG)

**Comment by DavidAnson** [comment]
Sounds like the same thing as #21.
