### ISSUE TITLE
Turn off tooltip showing which filters are being matched.

### ISSUE THREAD

**Issue by dharber** [TextAnalysisTool/Releases#49]
Most of the time, for me anyway, the information about which filter is being matched isn't very useful since it's readily discernible by looking at the line. On the other hand, having that box cover up lines around the cursor is very distracting.

It would be nice if there was an option to turn off the tooltip.

**Comment by dsp0105** [comment]
Yeah, I agree, tooltip showing the filters is not needed mostly as user already has colors defined for that filter, and distracting as it covers the lines.  Thanks for a wonderful tool!

**Comment by vincec-msft** [comment]
The 2018-01-03 release added a "Show Filter Tool Tip" preference that allows you to turn the tooltip on or off.

**Comment by dsp0105** [comment]
Thanks @vincec-msft , I am able to turn it off / on.
