### ISSUE TITLE
Divide by zero crash

### ISSUE THREAD

**Issue by avi-ms** [TextAnalysisTool/Releases#51]
TextAnalysisTool crashes with a divide by zero exception when I select a filter with 0 hits and press the space bar. Stack trace below

<img width="361" alt="tatexception" src="https://user-images.githubusercontent.com/34112944/39284032-3d56c4cc-48c6-11e8-9073-096bdf0dce17.png">

**Comment by DavidAnson** [comment]
That’s a pretty old version. Have you tried a newer one?

**Comment by avi-ms** [comment]
Confirmed the bug is patched in the 2018-01-03 release
