### ISSUE TITLE
Crash when closing on Windows Insider

### ISSUE THREAD

**Issue by jobarner** [TextAnalysisTool/Releases#52]
Everytime I close TextAnalysisTool.net, I get the below crash.
This is on Windows Insider Preview, build 17660.
Presumably, it's related to the new [Sets feature](https://insider.windows.com/en-us/articles/introducing-sets/).

> ---------------------------
> TextAnalysisTool.NET
> ---------------------------
> Sorry, an unhandled exception has occurred and the application is about to terminate!
> Please report this problem and include the following details:
> 
> TextAnalysisTool.NET, Version=1.0.6011.29276, Culture=neutral, PublicKeyToken=d0f1991e18299f1d - 2016-06-16
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at TextAnalysisTool.NET.MainWindow.get_DisplayAreaHeight()
>    at TextAnalysisTool.NET.MainWindow.OnLayout(LayoutEventArgs e)
>    at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
>    at System.Windows.Forms.Control.OnResize(EventArgs e)
>    at System.Windows.Forms.Form.OnResize(EventArgs e)
>    at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
>    at TextAnalysisTool.NET.MainWindow.OnSizeChanged(EventArgs e)
>    at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
>    at System.Windows.Forms.Control.UpdateBounds()
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.Form.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>

**Comment by DavidAnson** [comment]
Could you please report this via the Insiders program? It seems like a bad regression they won’t want to ship with. :(

**Comment by DavidAnson** [comment]
You might also try the latest version of TextAnalysisTool, but I don’t remember any fixes like this.

**Comment by vincec-msft** [comment]
It looks like the version listed is nearly 2 years old. Grab the latest from here: https://textanalysistool.github.io/

**Comment by jobarner** [comment]
This repro'd on version 2018-01-03.
However, it doesn't on Windows Insider build 17669, so I guess something was fixed in Windows itself.
