### ISSUE TITLE
Exception Opening Text File

### ISSUE THREAD

**Issue by PatrickRyder** [TextAnalysisTool/Releases#53]
I got an exception opening a text file from the File | Open menu (i.e. I already had a text file open).

The files I am opening are auto-generated by NLog from a Windows 10 application.  I have been opening hundreds of these files over recent months, so there shouldn't be anything strange in the file.

I have attached a screenshot of the exception.

![textanalysistoolerror](https://user-images.githubusercontent.com/13526323/39466698-2488ef82-4d22-11e8-8bfc-671dfaf6ba69.png)

**Comment by DavidAnson** [comment]
Download here: https://textanalysistool.github.io/
