### ISSUE TITLE
Add language/encoding detection when opening files [When there is Chinese in the log, it will be garbled.]

### ISSUE THREAD

**Issue by sincelh** [TextAnalysisTool/Releases#58]
When there is Chinese in the log, it will be garbled.

**Comment by vincec-msft** [comment]
See #42. Is this the same issue?

**Comment by sincelh** [comment]
It’s a bit similar, but not exactly the same. My log is encoded in GB2312, not UTF-8.

**Comment by sincelh** [comment]
It seems to display correctly, but it must be modified every time, which is a bit of a hassle. Can you let it automatically detect the encoding format?

**Comment by DavidAnson** [comment]
Language detection can be difficult. If you can change the creation of these files to output the BOM, it would benefit other tools as well. I will leave this open as a feature request. Thank you!

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.
