### ISSUE TITLE
UTF-8 encoding is not being read correctly

### ISSUE THREAD

**Issue by somasundarambk** [TextAnalysisTool/Releases#62]
We found that the time field is displayed with garbage characters before AM / PM when the log file is in UTF-8. Other text editors are able to parse this correctly. Changing the file format to non UTF-8 works with this tool too. Repro file attached
[SkypeRoom-Init-4.0.1.0.log](https://github.com/TextAnalysisTool/Releases/files/2866004/SkypeRoom-Init-4.0.1.0.log)

**Comment by DavidAnson** [comment]
That file does not have a UTF8 BOM: https://en.m.wikipedia.org/wiki/Byte_order_mark

If you add one (for example, Save As from Notepad), it will open and render as you expect in TextAnalysisTool.

Please see issue #58 for more about this.
