### ISSUE TITLE
Any existing TextAnalysisTool plugin?

### ISSUE THREAD

**Issue by rickhau** [TextAnalysisTool/Releases#63]
I saw the post by the author to give a very simple example to show how to write the plugin.
https://dlaa.me/blog/post/tatplugins

However, I am not able to find any real plugin for this tool.
Maybe I don't use the correct keyword. 
If someone knows any good plugin for this tool, could you please share here?

**Comment by DavidAnson** [comment]
I know of various teams that have created plug-ins for their own purposes, but they tend to be fairly specific. There is this plug-in that’s public, but it may not be of interest to you: https://dlaa.me/blog/post/10043509

**Comment by vincec-msft** [comment]
I saw one plugin that would convert timestamps to different time zones. That was pretty cool. Sadly, all plugins that I've seen have been private.
