### ISSUE TITLE
Can we save the filter panel width?

### ISSUE THREAD

**Issue by rickhau** [TextAnalysisTool/Releases#64]
Firstly, I love this tool to save my time for checking the logs.
However, I always need to adjust the width of each column in filter panel.

 Modifiers| Pattern| Description|Hits

![image](https://user-images.githubusercontent.com/1428231/55447899-49ce0680-55f8-11e9-8bf6-e24f880ba32d.png)

Do we have any option to deselect some column here? like I don't want to see the description or we can save the width I want so that I don't need to adjust the width of Pattern and description all the time when I open a new one.
It takes me some time to do it.

Note: for people who put the filter list location at the bottom, there might be no problem.
For me, I would prefer put it at the right of the window. it eats a lot of spaces.

**Comment by elmarlee** [comment]
+1

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.
