### ISSUE TITLE
Is there a command line option equivalent of "File -> Save Current Lines" without actually launching UI?

### ISSUE THREAD

**Issue by miDeepakH** [TextAnalysisTool/Releases#66]
Trying to parse a .csv file and save filtered content to a .txt file for further processing.
Looking for command line option to do same without need of launching UI.

**Comment by DavidAnson** [comment]
No, sorry, there is not.

**Comment by vincec-msft** [comment]
Isn't that "grep" or "findstr"? :)
But seriously, you want to pass a csv and a file that specifies the filters (x.tat) and have the tool apply that filters to the csv and save the results to a new file?

**Comment by miDeepakH** [comment]
Got too comfortable using TextAnalysisTool, that I missed out on looking for "grep" alternative on Windows :|
"findstr" serves the purpose :) Thanks
