### ISSUE TITLE
Can we hide filtered result? 

### ISSUE THREAD

**Issue by andyhuang55** [TextAnalysisTool/Releases#67]
The filtered result can be colored.  
However, sometimes it is very useful to hide some garbage messages base on keyword. 
Could you add a new option in the filter rule to hide the result.  

It may look like this:
<filter enabled="y" excluding="n" description="garbage message" backColor="f0e68c" type="matches_text" case_sensitive="n" regex="n" **hide="y"** text="garbage" />

**Comment by DavidAnson** [comment]
How is this different than an excluding filter?

**Comment by andyhuang55** [comment]
Thank you for your quick response. 

![TextAnalyseTool](https://user-images.githubusercontent.com/18101246/58148062-ce9bdf00-7c8f-11e9-82bc-8c24b5a214e4.png)

Excluding filter can solve some issues, but not 100% meet what I want. 
Please check the attached screen as example. 
I would like to :

1. hide any line contains "chatty  :"
2. highlight any line contains "ActivityThread"
3. still show other lines which does not meet 1 & 2.    So I can continue analyze other messages.

**Comment by DavidAnson** [comment]
This is a bit of a hack, but I think you could add a third filter to your example above that matches everything, use an excluding filter for #1, and that would get the result you want.

**Comment by andyhuang55** [comment]
thanks.  It works.
