### ISSUE TITLE
Suggestion to be able to hide all lines that do not match a filter.

### ISSUE THREAD

**Issue by PatrickRyder** [TextAnalysisTool/Releases#74]
This is not an issue, as such; it is a suggestion for a feature.

Often in log files, I like to tag all lines that belong to a single code module, and sometimes it would be nice to 'turn off' every message that doesn't belong to this module.

For example, if I have a log like this:

**|MESSAGING|Message from object 'Foo' received (payload='IsBusy').
|.....|A message from another code module.
|MESSAGING|Message from object 'Foo' received (payload='Locked').
|.....|A message from another code module.
|.....|A message from another code module.
|.....|A message from another code module.**

It would be nice if I could easily turn off the 'noise' and reduce the log to:

**|MESSAGING|Message from object 'Foo' received (payload='IsBusy').
|MESSAGING|Message from object 'Foo' received (payload='Locked').**

Maybe this is possible with the current filtering system but so far I have failed to figure out any way to do this that is convenient enough to be usable during a normal build-debug cycle.

**Comment by DavidAnson** [comment]
If I understand correctly, you should be able to add a filter for the lines you want to see and then use Ctrl+H to hide the unfiltered lines.

**Comment by PatrickRyder** [comment]
@DavidAnson 

Thank you for the answer, David. It does do roughly what I had in mind and is very useful.

Now you've told me about this, my No 1 feature request would be to have multiple filter files loaded, so I can quickly switch between them. :)

Kind wishes - Patrick

**Comment by DavidAnson** [comment]
Great, please open an issue for that?
