### ISSUE TITLE
Support docking the filter list to the right/left side of the window (in addition to the bottom)

### ISSUE THREAD

**Issue by DavidAnson** [TextAnalysisTool/Releases#8]

**Comment by bloodfluke** [comment]
Hi, David, any update of this issue? I think it's very required, thanks!

**Comment by DavidAnson** [comment]
No update so far, sorry. If/when the feature gets implemented, I'll close this issue so you'll know.

**Comment by bloodfluke** [comment]
Hi, David, thanks! Hope soon!

**Comment by DavidAnson** [comment]
Fixed in the 2016-06-16 release, thanks!
