### ISSUE TITLE
how to add a plug-ins to preprocessing the txt file.

### ISSUE THREAD

**Issue by kkswbq** [TextAnalysisTool/Releases#81]
I would like to merge some special lines to 1 line for TextAnalysisTool to handle.
Any explain about the interface about pulg-ins ?

  And more:  can i only display the word that matched not a whole line.

Bingqing

**Comment by DavidAnson** [comment]
Merging lines can be done with a plugin, more info here: https://dlaa.me/blog/tag/TextAnalysisTool

Highlighting part of a line is a feature request, kind of like issue #4.

**Comment by kkswbq** [comment]
many thanks , it worked.

Shortcut to download sample code.

https://dlaa.me/Samples/TextAnalysisTool.NET/SamplePlugins.zip

**Comment by kkswbq** [comment]
thanks.
