### ISSUE TITLE
Create a choco package

### ISSUE THREAD

**Issue by whihathac** [TextAnalysisTool/Releases#82]
A choco package would really be nice for installing this nifty tool.

**Comment by DavidAnson** [comment]
I know they're popular, but I don't personally recommend third-party installers. The ownership/security issues seem troublesome to me. I'll leave this issue open, though, if others want to comment.

**Comment by whihathac** [comment]
Yes, I can understand that. I personally use only official or (officially blessed) packages on Chocolate. More the reason to create a package officially owned (and managed) by you 😄. 

I've never created a chocolatey package before, but I can offer to lend help to create one for this tool. Seems very straight forward - https://github.com/chocolatey/choco/wiki/CreatePackages

**Comment by DavidAnson** [comment]
If you want to draft something, I’d be happy to have a look.

**Comment by whihathac** [comment]
Created a PR #83. Tested this locally and it works great :)

**Comment by DavidAnson** [comment]
Thanks! FYI, I will need a bit of time to review this and will probably have some questions for you.

**Comment by DavidAnson** [comment]
Today Microsoft came out pretty strongly against third-party package managers by announcing their own: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/

This was not something I was aware of and I’m curious how this will play out.

**Comment by whihathac** [comment]
Oh wow! This is very interesting 👍 I think it will take sometime for convergence but I am really happy that we decided to create central and official repo for this (taking a leaf out of Linux)

**Comment by whihathac** [comment]
I attended Scott's build session and he said they are working on plan to integrate with other package managers like Chocolatey.

**Comment by whihathac** [comment]
Looks like I should also create WinGet YAML file :) I'll see if I get a chance over the weekend.
