### ISSUE TITLE
Allow adding markers via menu bar

### ISSUE THREAD

**Issue by scaramushe** [TextAnalysisTool/Releases#87]
Add an option in the menu bar to add marker to current line
Usecase: people who work on a machine where keyboard shortcuts are challenging

Alternatively - allow changing the keyboard shortcuts to some custom ones that are better supported on a platform

**Comment by vincec-msft** [comment]
@scaramushe , could you please elaborate on this? You would find a menu item easier than these shortcuts:

**Comment by scaramushe** [comment]
The usecase I have in mind is when working via virtual machine, for example parallel on Mac, some keyboard shortcuts are not available. In such case it is impossible to use ctrl +1-8, so mouse menu would be a solution. Like I mentioned above, adding an option to override the default keyboard shortcuts is also a resolution. 
As for your exact question, there could be a menu item called “add marker” which would have a submenu with values 1-8

**Comment by vincec-msft** [comment]
Ah, makes sense. What would you remap things to if you could remap? Adding duplicate bindings may be easier than a full-on remapping feature.

**Comment by scaramushe** [comment]
Probably I’d use something that combines 3 keys- Alt Ctrl 1-8

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.
