### ISSUE TITLE
Add a refresh button or the ability to monitor active log files

### ISSUE THREAD

**Issue by linuxgurugamer** [TextAnalysisTool/Releases#88]

**Comment by DavidAnson** [comment]
`File | Reload` or `F5` reload the current file.

**Comment by linuxgurugamer** [comment]
Thank you, the F5 will work for now.  I'm using this to monitor a log file in real time, would be very helpful if it could someday watch an active log file

**Comment by vincec-msft** [comment]
Dupe of #7 ?

**Comment by DavidAnson** [comment]
Agreed, thanks @vincec-msft.
