### ISSUE TITLE
Quick find a filtered line in analyzed text.

### ISSUE THREAD

**Issue by WoodyKu** [TextAnalysisTool/Releases#89]
I use the tool for many years and have many .tat files with predefined filters.  In many cases the .tat file has a large number of filters (beyond the alphabet and numbers), so some filters may not have the markers (a,b,c, etc).  Hence finding a single line that corresponds to a particular filter I cannot use the marker letter.  Turning on/off multiple filters is cumbersome, so is the manual entering the text in the Find feature.
Here is a proposal for an enhancement:
Add new options in the Filter right-click menu: "Go to next" and "Go to previous".  Clicking on these options, would move to the next/previous line in the main window matching the selected filter.

**Comment by DavidAnson** [comment]
This should be fixed in the 2023-03-24 release available via <https://textanalysistool.github.io/>.
