### ISSUE TITLE
Make filter reordering easier

### ISSUE THREAD

**Issue by EdKaiser** [TextAnalysisTool/Releases#9]
If you have a lot of filters and add a new one, it is appended at the bottom of the list.  The only way to move it is to right-click and select 'move up', and repeat that until it is at the appropriate place in the list.

It would be great if there was an easier method for reordering the filters.  Perhaps keyboard shortcuts and/or buttons associated with the list.

**Comment by mike-mo** [comment]
Releases *newer* than 2015-02-26 support drag & drop.

**Comment by mike-mo** [comment]
Have a look at the newly published release, 2015-05-18. It will allow you to drag and drop filters, making re-ordering a lot easier.
