### ISSUE TITLE
download fail

### ISSUE THREAD

**Issue by moroal** [TextAnalysisTool/Releases#90]
https://raw.githubusercontent.com/TextAnalysisTool/Releases/master/TextAnalysisTool.NET.zip
can not open

**Comment by vincec-msft** [comment]
These are the download URLs:
https://github.com/TextAnalysisTool/Releases/raw/master/TextAnalysisTool.NET.zip
https://github.com/TextAnalysisTool/Releases/blob/master/TextAnalysisTool.NET.zip

Where did you see the githubusercontent.com URL listed?

**Comment by vincec-msft** [comment]
And I could download and open from the URL you provided. This must be an issue with your connection, not github or TAT.

**Comment by moroal** [comment]
Thanks for the reply.

I also can't open this url:
https://github.com/TextAnalysisTool/Releases/raw/master/TextAnalysisTool.NET.zip

because it jumped here 
https://raw.githubusercontent.com/TextAnalysisTool/Releases/master/TextAnalysisTool.NET.zip
I get the download link from this website:
https://textanalysistool.github.io/

Can I send a copy of the latest version to my mailbox? 
mr.ck@outlook.com

Thank you very much

**Comment by moroal** [comment]
> And I could download and open from the URL you provided. This must be an issue with your connection, not github or TAT.



> And I could download and open from the URL you provided. This must be an issue with your connection, not github or TAT.

Hi, the problem is still not solved, please take a look at the information I provided, thank you!

**Comment by DavidAnson** [comment]
As noted above, the main page is https://textanalysistool.github.io/ and it links to https://github.com/TextAnalysisTool/Releases/raw/master/TextAnalysisTool.NET.zip. That link is valid and the corresponding ZIP is well-formed:

```
david@host ~ % curl --output TextAnalysisTool.NET.zip --location https://github.com/TextAnalysisTool/Releases/raw/master/TextAnalysisTool.NET.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   157  100   157    0     0   1784      0 --:--:-- --:--:-- --:--:--  1784
100  329k  100  329k    0     0  1420k      0 --:--:-- --:--:-- --:--:-- 1420k
david@host ~ % zip -T TextAnalysisTool.NET.zip 
test of TextAnalysisTool.NET.zip OK
david@host ~ % 
```

Something seems to be blocking your access to GitHub, but that's not something we can troubleshoot in this issue.

**Comment by moroal** [comment]
Thank you. I have fixed this issue with vpn
