### ISSUE TITLE
Save dialog for changed filter annoying

### ISSUE THREAD

**Issue by paulelong** [TextAnalysisTool/Releases#92]
I have a bunch of saved filters.  I'll toggle the filters on/off based on what I'm looking for.  But when I exit it prompts me to save the filter.  I understand that you might want to save filters, but for 99% of the time I do not.  I tend to have 10-20 windows open at a time and so when I have to shutdown, it prompts me for each one.  The dialog save filter dialog does not come to the foreground, and even if it did I don't want to manually close each one.

I would like to propose a feature that does not prompt me to save filters.

**Comment by vincec-msft** [comment]
I can see a couple options:

1. Add a setting that would not “dirty” a filter when it is toggled.
2. Add “No to all” and “Yes to all” buttons on the save prompt dialog.

1 feels pretty narrow and 2 still has extra steps that could be avoided. Are there other ideas or does anyone have a preference for one of these?

**Comment by DavidAnson** [comment]
1 was my thought. 2 is cross-process and may be unnecessary after 1?

**Comment by vincec-msft** [comment]
Actually, we already have this option. Setting the "Mark Filters Changed" option to "AddRemoveEdit" will cause a prompt only if a filter is added, removed, or changed. Toggling the active state will not dirty the filter list.

Please reopen if this doesn't address your need.
