### ISSUE TITLE
garbled

### ISSUE THREAD

**Issue by moroal** [TextAnalysisTool/Releases#93]
How to solve Chinese garbled, please help me, thank u.

**Comment by moroal** [comment]
362 name:寰  packagename:com.tencent.weishi  version:8.26.1.588
just like this

**Comment by DavidAnson** [comment]
Make sure the file begins with a BOM so any Unicode characters are interpreted correctly. Maybe experiment with the font also?

https://en.m.wikipedia.org/wiki/Byte_order_mark

**Comment by vincec-msft** [comment]
Duplicate of #58
