### ISSUE TITLE
TextAnalysisTool Gives Error Applying Filter to Valid Text File

### ISSUE THREAD

**Issue by PatrickRyder** [TextAnalysisTool/Releases#95]
When attempting to open the attached text file (Output-Debug.txt) with the attached filter, I get the error below and an empty window is displayed. I get the same error if I attempt to open the file without specifying a **/Filters** argument.
![TextAnalysisToolError](https://user-images.githubusercontent.com/13526323/150324582-b9954cb8-89cc-41f9-b176-6e16f2c77aaa.png)
[TextAnalysisToolError.tat.txt](https://github.com/TextAnalysisTool/Releases/files/7904467/TextAnalysisToolError.tat.txt)
[Output-Debug.txt](https://github.com/TextAnalysisTool/Releases/files/7904471/Output-Debug.txt)

**Comment by DavidAnson** [comment]
The message is saying the error happened in the code for the custom filter "TripleAtLogsFilter". Have you debugged that first?

**Comment by PatrickRyder** [comment]
Hi, David,

I had completely forgotten that the filtering was now based on a custom C# file I had written! Doh!

It's only happened once in over a year. If it happens again, I'll read the instructions on how to debug a filter plugin, which I vaguely recall seeing somewhere.

Please close the issue and accept my apologies.

Kind wishes - Patrick

PS - I wish Microsoft had built your tool into VS2022. Long overdue. You can get extensions that do something similar but none is as easy and intuitive as yours to set up.


________________________________

**Comment by DavidAnson** [comment]
No worries! Just one crash in a year is a pretty good record. :)
